### ISSUE TITLE
v3.2.1: Errors when trying to use GatsbyPrismicImage fragments in GraphQL queries

### ISSUE THREAD

**Issue by jameskirkby** [angeloashmore/gatsby-source-prismic#274]
Bit of a weird one, I'm following the **Image processing** section from the README on a fairly new project. I'm getting a couple of errors which I can't see mentioned elsewhere.

Any ideas what the issue could be?

Gatsby version: 2.23.12

**Errors in GraphiQL:**

Example query:
```graphql
{
  allPrismicProject {
    edges {
      node {
        data {
          featured_image {
            fixed {
              ...GatsbyPrismicImageFixed
            }
          }
        }
      }
    }
  }
}
```
Response:
```json
{
  "errors": [
    {
      "message": "Unknown fragment \"GatsbyPrismicImageFixed\".",
      "locations": [
        {
          "line": 8,
          "column": 18
        }
      ],
      "stack": [
        "GraphQLError: Unknown fragment \"GatsbyPrismicImageFixed\".",
        "    at Object.FragmentSpread (/...hidden.../node_modules/graphql/validation/rules/KnownFragmentNames.js:29:29)",
        "    at Object.enter (/...hidden.../node_modules/graphql/language/visitor.js:324:29)",
        "    at Object.enter (/...hidden.../node_modules/graphql/language/visitor.js:375:25)",
        "    at visit (/...hidden.../node_modules/graphql/language/visitor.js:242:26)",
        "    at validate (/...hidden.../node_modules/graphql/validation/validate.js:73:24)",
        "    at /...hidden.../node_modules/express-graphql/index.js:121:32",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
      ]
    }
  ]
}
```

**Error in Console:**
(This happens when I change something in `gatsby-config.js` and save)
```
ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.base64`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.base64`.


 ERROR

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.base64`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.src`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.src`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFixedType.src`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.srcSet`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.srcSet`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFixedType.srcSet`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.srcWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.srcWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFixedType.srcWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.srcSetWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.srcSetWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFixedType.srcSetWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.sizes`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.sizes`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFixedType.sizes`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.width`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.width`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFixedType.width`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.height`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.height`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFixedType.height`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.base64`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.base64`.


 ERROR

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.base64`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.src`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.src`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFluidType.src`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.srcSet`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.srcSet`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFluidType.srcSet`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.srcWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.srcWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFluidType.srcWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.srcSetWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.srcSetWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFluidType.srcSetWebp`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.sizes`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.sizes`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFluidType.sizes`.


 ERROR

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.aspectRatio`.


 ERROR

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.aspectRatio`.


 ERROR

Field extension arguments must be provided as an object. Received "false" on `PrismicImageFluidType.aspectRatio`.
```

**Comment by angeloashmore** [comment]
I have seen this before as well. Can you confirm that the fragment exists and the site works on a fresh `gatsby develop`?

I was unable to narrow down where/why this is happening, primarily because the plugin does not set anything with the values `SEARCHABLE` or `SORTABLE`. I *think* this comes from Gatsby's ["fast filters" system](https://www.gatsbyjs.com/docs/query-filters/).

**Comment by jameskirkby** [comment]
Yep, just created a new site to double check, still the same issue. `package.json` from new site:

```
{
  ...
  "dependencies": {
    "gatsby": "^2.24.79",
    "gatsby-source-prismic": "^3.2.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  }
  ...
}
```

Couple of examples, one through a prismic slice and one without, same issue across both:

![Screenshot 2020-10-20 at 10 31 10](https://user-images.githubusercontent.com/6663840/96568100-78393280-12bf-11eb-8730-2f47fc7c2093.png)

Is there something I can do to list out all available fragments? Do I need to install any extra dependancies, such `gatsby-transformer-sharp` and `gatsby-plugin-sharp`, even if I'm not downloading the images for use that way?

**Comment by jameskirkby** [comment]
Minor update, fragments are working within Gatsby, just not in GraphiQL.

For example, in a component I can make this fragment:
```js
export const query = graphql`
  fragment Image on PrismicImageType {
    alt
    dimensions {
      height
      width
    }
    url
    fluid(srcSetBreakpoints: [400, 600, 800]) {
      aspectRatio
      base64
      src
      srcSet
    }
  }
```

Then across the site, I can then write something like this:
```js
export const PageQuery = graphql`
  query ExamplePage {
    prismicExamplePage {
      data {
        title {
          text
        }
        image {
          ...Image
        }
      }
    }
  }
`
```
The response to the above query will include all of the relevant IMGIX fields.

Closing as my issue is basically solved. The "Error in Console" mentioned above isn't breaking anything.

**Comment by Floriferous** [comment]
Would be nice if the error could be fixed in the console though right? We're running into the same issue.
