### ISSUE TITLE
GraphQL error: Cannot find ObjectTypeComposer with name JSON

### ISSUE THREAD

**Issue by frederickfogerty** [angeloashmore/gatsby-source-prismic#308]
Hey there @angeloashmore 👋 thanks so much for making this plugin!

I'm getting a small error when configuring this plugin with my Prismic site.

### Steps to reproduce

1. Add gatsby-source-prismic with the following config
```js
  {
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: // redacted,

        accessToken: // redacted,

        schemas: {
          page: require("./config/prismic/schemas/page.json"),
          menu: require("./config/prismic/schemas/menu.json"),
          homepage: require("./config/prismic/schemas/page.json"),
        },

        imageImgixParams: {
          auto: "compress,format",
          fit: "max",
          q: 50,
        },

        imagePlaceholderImgixParams: {
          w: 100,
          blur: 15,
          q: 50,
        },
      },
    },
```
2. Run `gatsby develop`

### Expected result

Server loads as normal

### Actual result

```
error Missing onError handler for invocation 'building-schema', error was 'Error: Cannot find ObjectTypeComposer with name JSON'. Stacktrace was 'Error: Cannot find ObjectTypeComposer with name JSON
    at SchemaComposer.getOTC (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql-compose/lib/SchemaComposer.js:463:11)
    at map (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/gatsby/src/schema/schema.js:620:32)
    at Array.map (<anonymous>)
    at types (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/gatsby/src/schema/schema.js:619:40)
    at _graphql.GraphQLUnionType._objectSpread.types (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql-compose/lib/UnionTypeComposer.js:78:99)
    at resolveThunk (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/definition.js:438:40)
    at defineTypes (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/definition.js:837:15)
    at GraphQLUnionType.getTypes (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/definition.js:806:26)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:272:28)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:272:39)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)'
```

![image](https://user-images.githubusercontent.com/615334/104638782-e450ea00-56a6-11eb-9f5c-5b1b148ba8de.png)

### Info

Gatsby CLI version: 2.17.1
Gatsby version: 2.29.0
gatsby-source-prismic version: 3.3.1

### Extra config info

`gatsby-config.js`

```js
const { ImgixSourceType } = require("@imgix/gatsby")

module.exports = {
  siteMetadata: {
    // redacted
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    "gatsby-transformer-json",
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: // redacted,

        accessToken: // redacted,

        schemas: {
          page: require("./config/prismic/schemas/page.json"),
          menu: require("./config/prismic/schemas/menu.json"),
          homepage: require("./config/prismic/schemas/page.json"),
        },

        imageImgixParams: {
          auto: "compress,format",
          fit: "max",
          q: 50,
        },

        imagePlaceholderImgixParams: {
          w: 100,
          blur: 15,
          q: 50,
        },
      },
    },
    {
      resolve: `@imgix/gatsby`,
      options: {
        domain: "sdk-proxy-test.imgix.net",
        secureURLToken: process.env.PROXY_DEMO_TOKEN,
        sourceType: ImgixSourceType.WebProxy,
        fields: [
          {
            nodeType: "Post",
            fieldName: "imgixImage",
            getURL: node => node.imageURL,
          },
        ],
      },
    },
  ],
}

```

**Comment by frederickfogerty** [comment]
Dupe of #309
