### ISSUE TITLE
GraphQL error: Cannot find ObjectTypeComposer with name JSON

### ISSUE THREAD

**Issue by frederickfogerty** [angeloashmore/gatsby-source-prismic#309]
Hey there @angeloashmore 👋 thanks so much for making this plugin!

I'm getting a small error when configuring this plugin with my Prismic site.

### Steps to reproduce

1. Add gatsby-source-prismic with the following config
```js
  {
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: // redacted,

        accessToken: // redacted,

        schemas: {
          page: require("./config/prismic/schemas/page.json"),
          menu: require("./config/prismic/schemas/menu.json"),
          homepage: require("./config/prismic/schemas/page.json"),
        },

        imageImgixParams: {
          auto: "compress,format",
          fit: "max",
          q: 50,
        },

        imagePlaceholderImgixParams: {
          w: 100,
          blur: 15,
          q: 50,
        },
      },
    },
```
2. Run `gatsby develop`

### Expected result

Server loads as normal

### Actual result

```
error Missing onError handler for invocation 'building-schema', error was 'Error: Cannot find ObjectTypeComposer with name JSON'. Stacktrace was 'Error: Cannot find ObjectTypeComposer with name JSON
    at SchemaComposer.getOTC (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql-compose/lib/SchemaComposer.js:463:11)
    at map (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/gatsby/src/schema/schema.js:620:32)
    at Array.map (<anonymous>)
    at types (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/gatsby/src/schema/schema.js:619:40)
    at _graphql.GraphQLUnionType._objectSpread.types (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql-compose/lib/UnionTypeComposer.js:78:99)
    at resolveThunk (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/definition.js:438:40)
    at defineTypes (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/definition.js:837:15)
    at GraphQLUnionType.getTypes (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/definition.js:806:26)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:272:28)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:272:39)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at typeMapReducer (/Users/fred/Programming/imgix/sdk-monorepo/js/packages/gatsby/test/dev-and-e2e/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)'
```

![image](https://user-images.githubusercontent.com/615334/104638782-e450ea00-56a6-11eb-9f5c-5b1b148ba8de.png)

### Info

Gatsby CLI version: 2.17.1
Gatsby version: 2.29.0
gatsby-source-prismic version: 3.3.1

### Extra config info

`gatsby-config.js`

```js
const { ImgixSourceType } = require("@imgix/gatsby")

module.exports = {
  siteMetadata: {
    // redacted
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    "gatsby-transformer-json",
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: // redacted,

        accessToken: // redacted,

        schemas: {
          page: require("./config/prismic/schemas/page.json"),
          menu: require("./config/prismic/schemas/menu.json"),
          homepage: require("./config/prismic/schemas/page.json"),
        },

        imageImgixParams: {
          auto: "compress,format",
          fit: "max",
          q: 50,
        },

        imagePlaceholderImgixParams: {
          w: 100,
          blur: 15,
          q: 50,
        },
      },
    },
    {
      resolve: `@imgix/gatsby`,
      options: {
        domain: // redacted,
        secureURLToken: process.env.PROXY_DEMO_TOKEN,
        sourceType: ImgixSourceType.WebProxy,
        fields: [
          {
            nodeType: "Post",
            fieldName: "imgixImage",
            getURL: node => node.imageURL,
          },
        ],
      },
    },
  ],
}

```

**Comment by frederickfogerty** [comment]
Hey @angeloashmore, thanks for the reply here. We are using a sort of "monorepo" (it's more just a separate package stored in a nested directory) but we aren't using Lerna or Yarn workspaces or anything like this. Still, I removed the parent `node_modules` to ensure this was a "clean" environment and I still had the issue.

Thanks for linking the issue. Unfortunately I tried updating the dependencies with no avail.

That would be great. I created a minimal repro that doesn't have any of the imgix in it, and has the latest dependencies and everything. You can find it [here](https://github.com/frederickfogerty/prismic-repro). You'll need to export two environment variables before it'll build, `PRISMIC_REPO_NAME` and `PRISMIC_ACCESS_TOKEN`

**Comment by angeloashmore** [comment]
@frederickfogerty Thanks, I'll take a look at that repo today and post updates here.

**Comment by angeloashmore** [comment]
I see in your JSON schemas that the slices are Shared Slices. Were these custom types created using Prismic's Slice Machine/Slice Builder? I believe Slice Builder is a Next.js and Nuxt.js-only product right now and does not yet have a Gatsby integration. As such, Shared Slices are not supported in `gatsby-source-prismic` at this time.

Thanks for sharing this, though. This is the first time I'm seeing a shared Slice in a schema so this will help when planning out how to support them in the future.

I replaced the schemas in your sample repo with a base one I use and it runs as expected. It includes an Images slice that can be used to test Imgix. The Page custom type will need to be updated in Prismic's UI with this JSON to work.

`page.json`:
```json
{
  "Main": {
    "title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1",
        "label": "Title",
        "placeholder": "Name of the page"
      }
    },
    "uid": {
      "type": "UID",
      "config": {
        "label": "UID",
        "placeholder": "Unique identifier for the URL"
      }
    },
    "parent": {
      "type": "Link",
      "config": {
        "select": "document",
        "customtypes": ["page"],
        "label": "Parent",
        "placeholder": "Optional - Parent of the page"
      }
    },
    "meta_title": {
      "type": "Text",
      "config": {
        "label": "Meta Title",
        "placeholder": "Optional - Override the publicly viewable page title"
      }
    },
    "meta_description": {
      "type": "Text",
      "config": {
        "label": "Meta Description",
        "placeholder": "Optional - One sentence description of the page's content"
      }
    },
    "redirect_to": {
      "type": "Link",
      "config": {
        "label": "Redirect To",
        "placeholder": "Optional - Redirect this page to another page or external URL"
      }
    },
    "redirect_is_permanent": {
      "type": "Boolean",
      "config": {
        "placeholder_false": "No",
        "placeholder_true": "Yes, redirect forever",
        "default_value": false,
        "label": "Redirect Is Permanent"
      }
    }
  },
  "Body": {
    "body": {
      "type": "Slices",
      "fieldset": "Slice zone",
      "config": {
        "labels": {
          "images": [],
          "text": [],
          "embed": [],
          "text_and_image": [],
          "anchor": []
        },
        "choices": {
          "text": {
            "type": "Slice",
            "fieldset": "Text",
            "description": "Rich text with headings and links",
            "icon": "text_fields",
            "display": "list",
            "non-repeat": {
              "text": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, heading1, strong, em, hyperlink, embed, list-item, o-list-item, o-list-item",
                  "allowTargetBlank": true,
                  "label": "Text",
                  "placeholder": "Text with formatting and rich content"
                }
              }
            },
            "repeat": {}
          },
          "images": {
            "type": "Slice",
            "fieldset": "Images",
            "description": "One or more images with optional captions",
            "icon": "burst_mode",
            "display": "grid",
            "non-repeat": {},
            "repeat": {
              "image": {
                "type": "Image",
                "config": {
                  "constraint": {
                    "width": 2000
                  },
                  "thumbnails": [],
                  "label": "Image"
                }
              },
              "caption": {
                "type": "StructuredText",
                "config": {
                  "single": "paragraph",
                  "label": "Caption",
                  "placeholder": "Optional - Caption below image"
                }
              }
            }
          },
          "anchor": {
            "type": "Slice",
            "fieldset": "Anchor",
            "description": "Page marker to jump a user down the page",
            "icon": "vertical_align_center",
            "display": "list",
            "non-repeat": {
              "id": {
                "type": "StructuredText",
                "config": {
                  "single": "paragraph",
                  "label": "ID",
                  "placeholder": "Text used in anchor link"
                }
              }
            },
            "repeat": {}
          }
        }
      }
    }
  }
}
```

**Comment by frederickfogerty** [comment]
Hey @angeloashmore, thanks so much for taking a look at this 🙌 . 

> Were these custom types created using Prismic's Slice Machine/Slice Builder?

Yeah they were I think.

> I believe Slice Builder is a Next.js and Nuxt.js-only product right now and does not yet have a Gatsby integration. As such, Shared Slices are not supported in gatsby-source-prismic at this time.

Oh okay I didn't realise this, thanks for pointing that out.

> Thanks for sharing this, though. This is the first time I'm seeing a shared Slice in a schema so this will help when planning out how to support them in the future.

You're welcome I guess! 😅 

> I replaced the schemas in your sample repo with a base one I use and it runs as expected. It includes an Images slice that can be used to test Imgix. The Page custom type will need to be updated in Prismic's UI with this JSON to work.

Okay that's great, thank you so much for doing this!
